version: '3.8'

services:
  e-banking-db:
    image: postgres:16
    container_name: e-banking-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ENSA
      POSTGRES_PASSWORD: ENSA
      POSTGRES_DB: E_BANKING
    volumes:
      # Utilisation d'un volume nommé pour ne pas perdre les données
      - db_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: crypto-redis
    ports:
      - "6379:6379"

volumes:
  db_data:


